### ISSUE TITLE
Real Examples

### ISSUE THREAD

**Issue by hoijui** [pchampin/sophia_rs#100] opened 2021-03-05 19:47 UTC
Looking at these examples:
https://docs.rs/sophia_api/0.6.2/sophia_api/graph/trait.Graph.html#examples

I ask myself.. how to actual do something there?
Though I am a seasoned C/C++/Java/... dev, I am new to rust. I got some stuff running that I wrote myself, but trying to use this library knocked me out. everything I try in this for loop, fails. I do not think it is meaningful to ask for specific things, as I would just run into the next one directly. It would be nice to have an example that actually does something with the data, like store into a vec or map.
Even better, a full tutorial!

.. or at least pointers to code - anywhere - that uses the library.

**Comment by pchampin** [comment] 2021-03-05 21:46
Thanks for your interest in Sophia. Indeed, documentation is not Sophia's strong suit at the moment, unfortunately.

I propose to close this issue as a duplicate of #14, but I promise to try and make some proper documentation soon.

**Closed** 2021-03-06 07:00 UTC
Labels: duplicate
